# Generated by Django 5.1.3 on 2024-12-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_event_image_alter_gallery_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripton', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
