# Generated by Django 5.1.3 on 2024-12-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_rename_descripton_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(null=True, upload_to='news'),
        ),
    ]
